/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface ChartComponent {
        "color": string;
        "name": string;
        "percentage": string;
        "size": string;
        "unit": string;
        "value": string;
    }
    interface ItemComponent {
        "name": string;
        "status": string;
    }
    interface ProgressComponent {
        "name": string;
        "percentage": string;
        "value": string;
    }
}
declare global {
    interface HTMLChartComponentElement extends Components.ChartComponent, HTMLStencilElement {
    }
    var HTMLChartComponentElement: {
        prototype: HTMLChartComponentElement;
        new (): HTMLChartComponentElement;
    };
    interface HTMLItemComponentElement extends Components.ItemComponent, HTMLStencilElement {
    }
    var HTMLItemComponentElement: {
        prototype: HTMLItemComponentElement;
        new (): HTMLItemComponentElement;
    };
    interface HTMLProgressComponentElement extends Components.ProgressComponent, HTMLStencilElement {
    }
    var HTMLProgressComponentElement: {
        prototype: HTMLProgressComponentElement;
        new (): HTMLProgressComponentElement;
    };
    interface HTMLElementTagNameMap {
        "chart-component": HTMLChartComponentElement;
        "item-component": HTMLItemComponentElement;
        "progress-component": HTMLProgressComponentElement;
    }
}
declare namespace LocalJSX {
    interface ChartComponent {
        "color"?: string;
        "name"?: string;
        "percentage"?: string;
        "size"?: string;
        "unit"?: string;
        "value"?: string;
    }
    interface ItemComponent {
        "name"?: string;
        "status"?: string;
    }
    interface ProgressComponent {
        "name"?: string;
        "percentage"?: string;
        "value"?: string;
    }
    interface IntrinsicElements {
        "chart-component": ChartComponent;
        "item-component": ItemComponent;
        "progress-component": ProgressComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "chart-component": LocalJSX.ChartComponent & JSXBase.HTMLAttributes<HTMLChartComponentElement>;
            "item-component": LocalJSX.ItemComponent & JSXBase.HTMLAttributes<HTMLItemComponentElement>;
            "progress-component": LocalJSX.ProgressComponent & JSXBase.HTMLAttributes<HTMLProgressComponentElement>;
        }
    }
}
